// 智子系统Web/诊断规则库/经验库/诊断规则列表/详情按钮
export const KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_DETAIL_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_DETAIL_BUTTON'
// 智子系统Web/诊断规则库/经验库/诊断规则列表/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_CREATE_BUTTON'
// 智子系统Web/诊断规则库/经验库/诊断规则列表/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_EDIT_BUTTON'
// 智子系统Web/诊断规则库/经验库/诊断规则列表/下线按钮
export const KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_DOWN_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_KNOWLEDGE_DOWN_BUTTON'

// 智子系统Web/诊断规则库/经验库/故障原因库/详情按钮
export const KNOWLEDGEBASE_HISTORICALDATA_CAUSE_DETAIL_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_CAUSE_DETAIL_BUTTON'
// 智子系统Web/诊断规则库/经验库/故障原因库/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_CAUSE_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_CAUSE_CREATE_BUTTON'
// 智子系统Web/诊断规则库/经验库/故障原因库/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_CAUSE_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_CAUSE_EDIT_BUTTON'
// 智子系统Web/诊断规则库/经验库/故障原因库/停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_CAUSE_STOP_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_CAUSE_STOP_BUTTON'

//智子系统Web/诊断规则库/经验库/测试方案库/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_CREATE_BUTTON'
//智子系统Web/诊断规则库/经验库/测试方案库/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_EDIT_BUTTON'
//智子系统Web/诊断规则库/经验库/测试方案库/停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_STOP_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_TESTSCHEME_STOP_BUTTON'

// 智子系统Web/诊断规则库/经验库/维修方案库/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_CREATE_BUTTON'
// 智子系统Web/诊断规则库/经验库/维修方案库/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_EDIT_BUTTON'
// 智子系统Web/诊断规则库/经验库/维修方案库/停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_STOP_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_REPAIRTEST_STOP_BUTTON'

// 智子系统Web/诊断规则库/逻辑库/DTC列表/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_DTC_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_DTC_CREATE_BUTTON'
// 智子系统Web/诊断规则库/逻辑库/DTC列表/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_DTC_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_DTC_EDIT_BUTTON'
// 智子系统Web/诊断规则库/逻辑库/DTC列表/停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_DTC_STOP_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_DTC_STOP_BUTTON'

// 智子系统Web/诊断规则库/逻辑库/WTI列表/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_WTI_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_WTI_CREATE_BUTTON'
// 智子系统Web/诊断规则库/逻辑库/WTI列表/编辑按钮
export const KNOWLEDGEBASE_HISTORICALDATA_WTI_EDIT_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_WTI_EDIT_BUTTON'
// 智子系统Web/诊断规则库/逻辑库/WTI列表/编辑业务属性按钮
export const KNOWLEDGEBASE_HISTORICALDATA_WTI_EDITPROPERTIES_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_WTI_EDIT_BUTTON'
// 智子系统Web/诊断规则库/逻辑库/WTI列表/启用停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_WTI_ENABLEDORDISCONTINUED_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_WTI_ENABLEDORDISCONTINUED_BUTTON'

// 智子系统Web/诊断规则库/基础库/零件库/新建按钮
export const KNOWLEDGEBASE_BASICDATA_PART_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_PART_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/零件库/编辑按钮
export const KNOWLEDGEBASE_BASICDATA_PART_EDIT_BUTTON = 'KNOWLEDGEBASE_BASICDATA_PART_EDIT_BUTTON'
// 智子系统Web/诊断规则库/基础库/零件库/停用按钮
export const KNOWLEDGEBASE_BASICDATA_PART_STOP_BUTTON = 'KNOWLEDGEBASE_BASICDATA_PART_STOP_BUTTON'

// 智子系统Web/诊断规则库/基础库/部位库/新建按钮
export const KNOWLEDGEBASE_BASICDATA_POSITION_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_POSITION_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/部位库/编辑按钮
export const KNOWLEDGEBASE_BASICDATA_POSITION_EDIT_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_POSITION_EDIT_BUTTON'
// 智子系统Web/诊断规则库/基础库/部位库/停用按钮
export const KNOWLEDGEBASE_BASICDATA_POSITION_STOP_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_POSITION_STOP_BUTTON'

// 智子系统Web/诊断规则库/基础库/失效模式库/新建按钮
export const KNOWLEDGEBASE_BASICDATA_FAILUREMODE_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_FAILUREMODE_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/失效模式库/停用按钮
export const KNOWLEDGEBASE_BASICDATA_FAILUREMODE_STOP_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_FAILUREMODE_STOP_BUTTON'

// 智子系统Web/诊断规则库/基础库/工况列表/新建按钮
export const KNOWLEDGEBASE_BASICDATA_PERFORMANCE_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_PERFORMANCE_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/工况列表/停用按钮
export const KNOWLEDGEBASE_BASICDATA_PERFORMANCE_STOP_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_PERFORMANCE_STOP_BUTTON'

// 智子系统Web/诊断规则库/基础库/故障症状库/新建按钮
export const KNOWLEDGEBASE_BASICDATA_FAULTSYMPTOMS_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_FAULTSYMPTOMS_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/故障症状库/停用按钮
export const KNOWLEDGEBASE_BASICDATA_FAULTSYMPTOMS_STOP_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_FAULTSYMPTOMS_STOP_BUTTON'

// 智子系统Web/诊断规则库/基础库/故障现象库/新建按钮
export const KNOWLEDGEBASE_BASICDATA_SYMPTOMS_CREATE_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_SYMPTOMS_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/故障现象库/停用按钮
export const KNOWLEDGEBASE_BASICDATA_SYMPTOMS_STOP_BUTTON =
  'KNOWLEDGEBASE_BASICDATA_SYMPTOMS_STOP_BUTTON'
// 智子系统Web/诊断规则库/审批管理/审批列表/审批按钮
export const KNOWLEDGEBASE_APPROVAL_EXAMINE_BUTTON = 'KNOWLEDGEBASE_APPROVAL_EXAMINE_BUTTON'
// 智子系统Web/诊断规则库/审批管理/审批列表/详情按钮
export const KNOWLEDGEBASE_APPROVAL_DETAIL_BUTTON = 'KNOWLEDGEBASE_APPROVAL_DETAIL_BUTTON'

// 智子系统Web/诊断规则库/基础库/用户感知症状库/新建按钮
export const KNOWLEDGEBASE_HISTORICALDATA_PERCEPTION_CREATE_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_PERCEPTION_CREATE_BUTTON'
// 智子系统Web/诊断规则库/基础库/用户感知症状库/停用按钮
export const KNOWLEDGEBASE_HISTORICALDATA_PERCEPTION_STOP_BUTTON =
  'KNOWLEDGEBASE_HISTORICALDATA_PERCEPTION_STOP_BUTTON'
